kind: pipeline
type: docker
name: version-8.6-rc1

trigger:
  branch:
    - '8.6-rc1'
  event:
    - push
    - pull_request

# Validate version branch builds without publishing
steps:
  - name: v8.6-rc1-docker-image-build
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      platforms:
        - linux/amd64
      repo: kernel528/redis
      tags:
        - '8.6-rc1-branch-${DRONE_BUILD_NUMBER}-amd64'
      dry_run: true
---

kind: pipeline
type: docker
name: version-8

trigger:
  branch:
    - '8'
  event:
    - push
    - pull_request

# Build the docker image for amd64 architecture
steps:
  - name: v8-docker-image-build
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    when:
      event:
        - pull_request
    settings:
      platforms:
        - linux/amd64
      repo: kernel528/redis
      tags:
        - '8.6-rc1-pr-${DRONE_PULL_REQUEST}-amd64'
      dry_run: true

  - name: v8-docker-image-build-release
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    when:
      event:
        - push
    settings:
      platforms:
        - linux/amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/redis
      tags:
        - '8'
        - '8.6-rc1'
        - '8.6-rc1-drone-build-${DRONE_BUILD_NUMBER}-amd64'

  # Test docker image
  - name: v8-docker-test
    image: kernel528/redis:8.6-rc1
    when:
      branch:
        - '8'
      event:
        - push
    commands:
      - redis-server --version
      - redis-server --daemonize yes --bind 127.0.0.1 --port 6379 --dir /tmp
      - 'for i in 1 2 3 4 5; do redis-cli ping && break; sleep 1; done'
      - redis-cli set smoke_test ok
      - redis-cli get smoke_test
      - redis-cli shutdown

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts
---

kind: pipeline
type: docker
name: main-redis-amd64

trigger:
  event:
    - push
    - tag
  branch:
    - main

# Build the docker image for the main branch & tagged release
steps:
  - name: main-docker-image-build
    image: plugins/docker
    when:
      event:
        - push
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/redis
      tags:
        - latest

  - name: main-docker-image-build-tag
    image: plugins/docker
    when:
      event:
        - tag
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/redis
      tags:
        - '${DRONE_TAG}'

  # Test docker image
  - name: latest-docker-test
    image: kernel528/redis:latest # Construct the test image path dynamically
    when:
      branch:
        - main
      event:
        - push
    commands:
      - redis-server --version
      - redis-server --daemonize yes --bind 127.0.0.1 --port 6379 --dir /tmp
      - 'for i in 1 2 3 4 5; do redis-cli ping && break; sleep 1; done'
      - redis-cli shutdown

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts
