kind: pipeline
type: docker
name: redis-amd64

trigger:
  branch:
    - '8'
  event:
    - pull_request

# Build the docker image for amd64 architecture
steps:
  - name: amd64-image-build
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      platforms:
        - linux/amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/redis
      tags:
        - latest
        - '8'
        - '8.2.2'
        - '8.2.2-drone-build-${DRONE_BUILD_NUMBER}-amd64'

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts
---

kind: pipeline
type: docker
name: main-redis-amd64

trigger:
  event:
    - push
    - tag
  branch:
    - main

# Build the docker image for the main branch & tagged release
steps:
  - name: main-docker-image-build
    image: plugins/docker
    when:
      event:
        - tag
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/redis
      tags:
        - ${DRONE_TAG}

  # Test docker image
  - name: latest-redis-amd64-test
    image: kernel528/redis:latest # Construct the test image path dynamically
    when:
      branch:
        - main
      event:
        - push
    commands:
      - cat /etc/alpine-release
      - uname -a
      - redis-cli --version

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts